package quotes;

import java.util.ArrayList;
import java.util.Objects;

public class DataForTest {

    public static boolean isAuthorInJsonFile(String authorName){
        ArrayList<String> allAuth = new ArrayList<String>();
        allAuth.add("Marilyn Monroe");
        allAuth.add("Charles Dickens");
        allAuth.add("Charles Dickens");
        allAuth.add("George Orwell");
        allAuth.add("Judy Yogev");
        allAuth.add("George Orwell");
        allAuth.add("author");
        allAuth.add("Erik Pevernagie");
        allAuth.add("Miguel Ruiz");
        allAuth.add("Anton Chekhov");
        allAuth.add("Chuck Klosterman");
        allAuth.add("George Orwell");
        allAuth.add("author");

        allAuth.add("S.A. McAuley");
        allAuth.add("S.A. McAuley");
        allAuth.add("George Orwell");
        allAuth.add("V.E. Schwab");
        allAuth.add("John Keats");
        allAuth.add("V.E. Schwab");
        allAuth.add("办理马凯特大学毕业证[学历认证Marquette University");
        allAuth.add("Richard Rider");
        allAuth.add("Jane Austen");
        allAuth.add("办理贝勒大学毕业证[学历认证 Baylor University");
        allAuth.add("Tere Liye");
        allAuth.add("Susanna Kaysen");
        allAuth.add("강예빈");
        allAuth.add("강예빈팀장");
        allAuth.add("강예빈팀장");
        allAuth.add("강예빈팀장");
        allAuth.add("Richard Rider");
        allAuth.add("Charles Dickens");
        allAuth.add("Charles Dickens");
        allAuth.add("Richard Rider");
        allAuth.add("Robert Frost");
        allAuth.add("Cassandra Clare");
        allAuth.add("Cassandra Clare");
        allAuth.add("Nayyirah Waheed");
        allAuth.add("Cassandra Clare");
        allAuth.add("Cassandra Clare");
        allAuth.add("Cassandra Clare");
        allAuth.add("Nayyirah Waheed");
        allAuth.add("Steve Maraboli");
        allAuth.add("Nâzım Hikmet");
        allAuth.add("Nayyirah Waheed");
        allAuth.add("Leo Tolstoy");
        allAuth.add("Marcus Tullius Cicero");
        allAuth.add("Anthony Doerr");
        allAuth.add("密西西比州立大学文凭办理毕业证大学成绩单GPA");
        allAuth.add("Никола Вапцаров");
        allAuth.add("Richard Rider");
        allAuth.add("C.S. Lewis");
        allAuth.add("Conan O\u0027Brien");
        allAuth.add("J.K. Rowling");
        allAuth.add("办理密歇根州立大学毕业证[学历认证Michigan State University");
        allAuth.add("Mae West");
        allAuth.add("Marcus Tullius Cicero");
        allAuth.add("Bernard M. Baruch");
        allAuth.add("William W. Purkey");
        allAuth.add("Frank Zappa");
        allAuth.add( "Albert Einstein");
        allAuth.add("Marilyn Monroe");
        allAuth.add(  "Dr. Seuss");
        allAuth.add( "办理印地安那大学伯明顿分校毕业证[学历认证Indiana University,Bloomington");
        allAuth.add( "Oliver Bowden");
        allAuth.add("Markus Zusak");
        allAuth.add("Paulo Coelho");
        allAuth.add( "Robert Louis Stevenson");
        allAuth.add( "Patrick Ness");
        allAuth.add("T.J. Klune");
        allAuth.add("Chimamanda Ngozi Adichie");
        allAuth.add("T.J. Klune");
        allAuth.add("John Berger");
        allAuth.add( "T.J. Klune");
        allAuth.add("John Berger");
        allAuth.add( "T.J. Klune");
        allAuth.add(  "Stanley Kubrick");
        allAuth.add("John Berger");
        allAuth.add("John Stuart Mill");
        allAuth.add("George R.R. Martin");
        allAuth.add("Nassim Nicholas Taleb");
        allAuth.add("Conan O\u0027Brien");
        allAuth.add("Gregory David Roberts");
        allAuth.add("Graham Greene");
        allAuth.add("Nassim Nicholas Taleb");
        allAuth.add("T.J. Klune");
        allAuth.add( "Gregory David Roberts");
        allAuth.add("Martin Luther King Jr.");
        allAuth.add("Marcus Aurelius");
        allAuth.add("John Provan");
        allAuth.add("John Stuart Mill");
        allAuth.add( "Frank Herbert");
        allAuth.add("L.P. Hartley");
        allAuth.add("Conan O\u0027Brien");
        allAuth.add( "Rosie Nguyễn");
        allAuth.add("Jean-Paul Sartre");
        allAuth.add("Patrick Ness");
        allAuth.add( "Dante Alighieri");
        allAuth.add( "办理南卫理公会大学毕业证[学历认证Southern Methodist University");
        allAuth.add("Leigh Bardugo");
        allAuth.add("Patrick Ness");
        allAuth.add("Vasso Charalambous");
        allAuth.add("Marcus Aurelius");
        allAuth.add("办理迈阿密大学牛津分校毕业证[学历认证Miami University,Oxford");
        allAuth.add("Patrick Ness, A MONSTER CALLS");
        allAuth.add("Eleanor Roosevelt");
        allAuth.add( "Ilika Ranjan");
        allAuth.add( "Yrsa Daley-Ward");
        allAuth.add( "Harper Lee");
        allAuth.add( "Miguel Ruiz");
        allAuth.add("James M. Kouzes");
        allAuth.add("办理德州A\u0026M大学毕业证[学历认证Texas A\u0026M University");
        allAuth.add("Patrick Ness");
        allAuth.add("Emily Brontë");
        allAuth.add("办理佩斯大学毕业证[学历认证Pace University");
        allAuth.add("Patrick Ness");
        allAuth.add("Malcolm Gladwell");
        allAuth.add("Patrick Ness");
        allAuth.add("Tove Jansson");
        allAuth.add("Mark Lawrence");
        allAuth.add("Aleksandr Solzhenitsyn");
        allAuth.add("Mark Lawrence");
        allAuth.add("Patrick Ness");
        allAuth.add("Patrick Ness");
        allAuth.add("Patrick Ness");
        allAuth.add("Patrick Ness");
        allAuth.add("Carl Sagan");
        allAuth.add("Patrick Ness");
        allAuth.add("Arthur Schopenhauer");
        allAuth.add("Patrick Ness");
        allAuth.add("Charles Bukowski");
        allAuth.add("부산경마결과 【 MaSUN . K R 】 경마예상지");
        allAuth.add("Graham Greene");
        allAuth.add("Peter Cameron");
        allAuth.add("Patrick Ness");
        allAuth.add("Gabriel Bá");
        allAuth.add("Tove Jansson");
        allAuth.add("办理明尼苏达大学双城分校毕业证[学历认证University of Minnesota Twin Cities");
        allAuth.add("Ron Swanson");
        allAuth.add("Geeks");
        allAuth.add("for");
        allAuth.add("Geeks");
        return allAuth.contains(authorName);
    }
}
